sudo: required
services:
  - docker

before_install:
  - docker build -t ramanuja1990/docker-react -f Dockerfile.dev . 

script:
  - docker run ramanuja1990/docker-react npm run citest

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env-2"
  bucket_name: "elasticbeanstalk-us-east-1-072743567025"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY